name: "Build and deploy docs pages"

on: 
  push:
    branches:
      - doc-rest-migration

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install doxygen

      - name: "Checkout"
        uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false

      - name: "Setup python for sphinx"
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: "Install python dependencies"
        run: |
          pip3 install setuptools six
          pip3 install sphinx sphinx-rtd-theme
          pip3 install guzzle_sphinx_theme
          pip3 install sphinx-fortran
          pip3 install sphinx_sitemap
          # pip3 install sphinx-mathjax-offline

      - name: "Build sphinx doc"
        run: |
          cd CGNS-ReST-site
          chmod +x build.sh
          ./build.sh
        shell: bash
      
      - name: "Deploy"
        run: |
          cd CGNS-ReST-site
          git clone -b gh-pages --single-branch https://github.com/CGNS/cgns-modern.github.io.git docs/_build/deploy
          rsync -q -av --checksum --progress docs/_build/html/ docs/_build/deploy
          cd docs/_build/deploy
          git config --global user.name 'autopages'
          git config --global user.email 'cgns@users.noreply.github.com'
          git add --all .
          git commit -m "Update gh-pages"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git push
        shell: bash





